package com.net2plan.research.metrohaul.networkModel;

import java.util.Arrays;
import java.util.List;

public class WNetConstants
{
	public static String WNODE_NAMEOFANYCASTORIGINNODE = "ANYCASTORIGIN" + WNetConstants.LISTSEPARATORANDINVALIDNAMECHARACTER;
	public static String WNODE_NAMEOFANYCASTDESTINATION = "ANYCASTDESTINATION" + WNetConstants.LISTSEPARATORANDINVALIDNAMECHARACTER;
	public static String LISTSEPARATORANDINVALIDNAMECHARACTER = ",";
	static boolean WNODE_DEFAULT_ISCONNECTEDTOCORE = false;
	static double WFIBER_DEFAULT_ATTCOEFFICIENTDBPERKM = 0.25;
	static double WFIBER_DEFAULT_PMDCOEFF_PSPERSQRKM = 0.5;
	static double WFIBER_DEFAULT_CDCOEFF_PSPERNMKM = 15;
	static double WFIBER_DEFAULT_AMPLIFIERGAIN_DB = 15;
	static double WFIBER_DEFAULT_AMPLIFIERPMD_PS = 15;
	
	static double WFIBER_DEFAULT_PROPAGATIONSPEEDKMPERSEC = 200000;
	static List<Double> WFIBER_DEFAULT_VALIDOPTICALSLOTRANGES = Arrays.asList(1.0,320.0);
	static boolean WLPREQUEST_DEFAULT_ISTOBE11PROTECTED = false;
	static boolean WSERVICECHAINREQUEST_DEFAULT_ISENDEDINCORENODE = false;
	
}
