package com.net2plan.research.metrohaul.networkModel;

import java.util.Arrays;
import java.util.List;

public class WNetConstants
{
	public static String WNODE_NAMEOFANYCASTORIGINNODE = "ANYCASTORIGIN" + WNetConstants.WNODE_NODENAMEINVALIDCHARACTER;
	public static String WNODE_NAMEOFANYCASTDESTINATION = "ANYCASTDESTINATION" + WNetConstants.WNODE_NODENAMEINVALIDCHARACTER;
	public static String WNODE_NODENAMEINVALIDCHARACTER = ",";
	static boolean WNODE_DEFAULT_ISCONNECTEDTOCORE = false;
	static double WFIBER_DEFAULT_ATTCOEFFICIENTDBPERKM = 0.25;
	static double WFIBER_DEFAULT_PROPAGATIONSPEEDKMPERSEC = 200000;
	static List<Double> WFIBER_DEFAULT_VALIDOPTICALSLOTRANGES = Arrays.asList(1.0,320.0);
	static boolean WLPREQUEST_DEFAULT_ISTOBE11PROTECTED = false;
	static boolean WSERVICECHAINREQUEST_DEFAULT_ISENDEDINCORENODE = false;
	
}
